### ISSUE TITLE
Plugin Crash but Stand Alone Works

### ISSUE THREAD

**Issue by DrJeff** [damianxd/homebridge-vera#11]
@damianxd 
When using the plugin version does the plugin load all the devices unlike the standalone which only loads the rooms as a separate bridge? It seams that I get a crash as plugin because it's trying to dump all my devices at once and it can not handle even with the sync-request. Any solutions to bridge the plugin version to the Veras rooms?

**Comment by damianromanowski** [comment]
@DrJeff How many devices do you have? I had no issues importing any.

**Comment by DrJeff** [comment]
@damianromanowski  Ungrouped there are 129 total is the ceiling 100? I tried making a smaller chunks is that how the stand alone is working?

**Comment by damianromanowski** [comment]
@DrJeff Oh wow, that is indeed a lot. I only imported about 20 devices since most of my lights are handled by the Hue bridge. I think I have 5 dimmable lights that are pure z-wave, along with door/window/motion sensors.

My devices weren't grouped by rooms and I'm running the latest version as a plugin - not standalone. I only have one parent device, the homebridge device. Not sure why it's failing for you. Perhaps the author can chime in... @damianxd

**Comment by damianxd** [comment]
I have never tried that much devices with this program, standalone works with separated rooms if you set that up on the config, it is the default setting. Homebridge works a little like the same, but with just one big room holding all the devices.

I think your best chance is to use standalone until hombridge itself can work with a long list like that.
