### ISSUE TITLE
Missing garage_door.js

### ISSUE THREAD

**Issue by claymca** [damianxd/homebridge-vera#171]
I have Homebridge running but I can not see my garage door opener. Looking in lib/types/  I don't have garage_door.js. How do I get that installed?

**Comment by drewcovi** [comment]
@knodd should have a fork for you. And I’ll look into merging it this week. It’s long overdue. Just making sure it doesn’t conflict with existing code.

**Comment by claymca** [comment]
So I have the fork uploaded to but how do I install it so that it replace the previous Homebridge-vera

**Comment by drewcovi** [comment]
Hi @claymca the fork should be near identical to this one. Simply use it instead of this in the same way you installed this plugin.

**Comment by claymca** [comment]
Now I getting the following: 
<img width="831" alt="Screen Shot 2019-05-01 at 12 20 20 AM" src="https://user-images.githubusercontent.com/31967137/57005592-1ce52300-6ba7-11e9-8bcd-de6cfa19952e.png">

**Comment by drewcovi** [comment]
Hey @claymca totally been where you’ve been, but at this point you’re probably going to want to start consulting stackoverflow.

Fair to assume you’re new to npm?

Your output above is fine but you didn’t actually install someone else’s branch. You’re still installing this repository. 

The first error you see is because you typed `sudo` twice. And Sudo isn’t a package thus doesn’t have any package.json
