### ISSUE TITLE
Home temperatures way off

### ISSUE THREAD

**Issue by tamorgen** [damianxd/homebridge-vera#34]
Homebridge is importing various temperatures, and they are at least 100 degrees off.  In Vera, I have the Wunderground Weather Plugin installed, and VeraConnect WWN (Works with Nest).  The temperatures imported from these plug-ins are reading 160 or more.

I've seperately installed the homebridge-nest plugin, which uses the Nest API, and it's temperatures are correct.

**Comment by drewcovi** [comment]
It's likely you're in Fahrenheit and the folks maintaining this aren't. Regardless of the setting on your Vera, HomeKit expects Celsius. So some conversion is needed for both sensors and thermostats.

**Comment by drewcovi** [comment]
@tamorgen, I'm guessing your issue should be resolved now.  We've seen the conversion methods implemented both in thermostats and in temp sensors. That said, I **strongly** recommend adding your Nest thermostat to the **ignoredevices** list, because the WWN plugin uses the Nest REST API.

Sounds trivial but unfortunately that API is severely rate limited, and the HomeKit controls are built to send a slew of requests as you slide up and down the temperature gauge.

**INSTEAD:** please consider the homebridge-nest (https://github.com/KraigM/homebridge-nest) for this one device. It uses the firebase API which is a LOT more responsive and direct (although it is a grizzly bear to implement, so follow the instructions).
