### ISSUE TITLE
Is there a way to delay startup?

### ISSUE THREAD

**Issue by reallybman** [damianxd/homebridge-vera#64]
All - is there a way to delay the initial startup of homebridge? I find that if both vera and pi lose power, and reboot at the same time, homebridge will fail because the vera hasn't finished booting when pi begins looking for devices.

**Comment by djrobx** [comment]
I just put mine in a startup script (instead of automatic service startup), and added a sleep command. 

Even if you left the automatic service startup alone, you could add a startup script that sleeps, then restarts the service after a few seconds.

My script won't help you though since I am on FreeBSD.
