### ISSUE TITLE
Dimmers turn on at 100%

### ISSUE THREAD

**Issue by reallybman** [damianxd/homebridge-vera#99]
I'm finding that if you ask Siri to turn on a dimmer switch to a certain percentage, it will, for a second, flash at that correct percentage and then go to 100%.

**Comment by drewcovi** [comment]
@reallybman yeah, this has a lot to do with the fact that:

1. homekit sends **two** requests with any light that's off.
1. Vera can't seem to handle simply turning a light back **on** without setting it to 100%.

The logical thing to do is simply ignore the **on** command for setting dimmer level, since Vera doesn't need an additional request to turn on the power. But by the time the vera plugin is handling requests, there's no clear way to trace each (power plus dimmer) request back to the original request.

And the last thing we want to do is ignore the **on** request if the original request was just **on/off**

**Comment by djrobx** [comment]
>And the last thing we want to do is ignore the on request if the original request was just on/off

Right, this is definitely a vera issue.    The best compromise I came up with is to never send "On", but always send Vera another dim request to the last known dimmer level when you get an "On" request.  

If the "dimmer delay function" was working this would work even better - if the plugin got "On" and then a dim level set in rapid succession, after a small delay only the desired dim level would be sent out to Vera.

**Comment by drewcovi** [comment]
@djrobx, @reallybman mind beta testing master? pushed a few fixes, seem to be working for me at the moment.

**Comment by djrobx** [comment]
@drewcovi For sure, I'm way overdue in updating mine with your latest fixes anyway.    I'll test tomorrow and let you know if I see any issues

**Comment by reallybman** [comment]
@drewcovi Good work. The dimmers are setting correctly with a call from the off setting. Noticed that when asking for a group of lights to turn on or off (like "turn on livingroom lights"), where multiple devices are grouped together, not all the lights dim properly to the same percentage.

**Comment by drewcovi** [comment]
@reallybman correct. This will ensure that the lights behave more like any leviton dimmer (and perhaps others) that retain the "on level" for simple power state changes. 

The fact Vera forces 100% for any "on" command is actually something I'd like to better understand. Suffice to say if you tell Siri to turn the lights "all the way on" I believe this will always give you what you expect.

**Comment by drewcovi** [comment]
closing for now folks, let me know if theres something else here.
